# Generated by Django 5.2.10 on 2026-02-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='orders_paym_order_i_e3de73_idx',
            old_name='orders_paym_order_i_4513a0_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='orders_paym_provide_1220b3_idx',
            old_name='orders_paym_provide_226197_idx',
        ),
    ]
