# Generated by Django 5.2.10 on 2026-02-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_orders_paym_order_i_4513a0_idx_orders_paym_order_i_e3de73_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('payment_failed', 'Payment failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=32),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_id'], name='orders_paym_externa_549d50_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='uniq_pending_payment_per_order'),
        ),
    ]
