# Generated by ChatGPT

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppearancePreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "preset_type",
                    models.CharField(
                        choices=[
                            ("catalog_card", "Catalog card"),
                            ("product_page", "Product page"),
                            ("product_card", "Product card"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["preset_type", "name", "id"],
                "indexes": [models.Index(fields=["is_published", "preset_type"], name="app_preset_scope_type_idx")],
            },
        ),
        migrations.CreateModel(
            name="ShopAppearanceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_published", models.BooleanField(unique=True)),
                ("theme_mode", models.CharField(choices=[("light", "Light"), ("dark", "Dark")], default="light", max_length=16)),
                ("primary_color", models.CharField(default="#ff6b00", max_length=7)),
                (
                    "grid_columns",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)],
                    ),
                ),
                (
                    "card_height",
                    models.PositiveIntegerField(
                        default=320,
                        validators=[django.core.validators.MinValueValidator(240), django.core.validators.MaxValueValidator(520)],
                    ),
                ),
                (
                    "spacing_level",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_catalog_preset",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="appearance.appearancepreset"),
                ),
                (
                    "active_product_card_preset",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="appearance.appearancepreset"),
                ),
                (
                    "active_product_page_preset",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="appearance.appearancepreset"),
                ),
            ],
            options={
                "ordering": ["is_published"],
            },
        ),
        migrations.CreateModel(
            name="AppearanceBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("image_url", models.URLField(max_length=1000)),
                ("link_url", models.URLField(max_length=1000)),
                (
                    "placement",
                    models.CharField(
                        choices=[("below_header", "Below header"), ("in_grid", "In grid")],
                        max_length=32,
                    ),
                ),
                ("after_row", models.PositiveIntegerField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [models.Index(fields=["is_published", "is_enabled"], name="app_banner_scope_enabled_idx")],
                "constraints": [
                    models.CheckConstraint(
                        check=(
                            models.Q(placement="below_header", after_row__isnull=True)
                            | models.Q(placement="in_grid", after_row__gte=1)
                        ),
                        name="appearance_banner_placement_rule",
                    )
                ],
            },
        ),
    ]
