# Generated by Django 5.2.10 on 2026-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appearancebanner',
            name='appearance_banner_placement_rule',
        ),
        migrations.AddConstraint(
            model_name='appearancebanner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('placement', 'below_header'), ('after_row__isnull', True)), models.Q(('placement', 'in_grid'), ('after_row__gte', 1)), _connector='OR'), name='appearance_banner_placement_rule'),
        ),
    ]
