# Generated by Django 5.2.10 on 2026-02-27 10:30

import online_store_backend.appearance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appearance", "0002_remove_appearancebanner_appearance_banner_placement_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopappearancesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="appearance/logos/",
                validators=[online_store_backend.appearance.validators.validate_logo_file],
            ),
        ),
    ]
